### ISSUE TITLE
Permission denied error when running?

### ISSUE THREAD

**Issue by JizzyOnGithub** [andreykaere/ixwindow#12]
I did everything you said with cloning the repo and installing then whenever I try to run my launch.sh i get:

/bin/sh: 1: /home/[my username]/ixwindow: Permission denied

I'm noob pls help

**Comment by andreykaere** [comment]
What is "launch.sh"? What does it do?

**Comment by JizzyOnGithub** [comment]
do you have discord so I can message you? I can't figure out how to properly set this up

**Comment by andreykaere** [comment]
You can write everything you want here, in the comment section. If you need, you can apply recording of your screen as well, if you feel like you need it.
