### ISSUE TITLE
Xmonad support

### ISSUE THREAD

**Issue by LoydAndrew** [andreykaere/ixwindow#13]
Any way xmonad support could be implemented?

**Comment by andreykaere** [comment]
I don't know if there is an `ipc` for xmonad, that can be implemented in Rust. And I don't think that I can implement functionality of "hiding" the icon, when window becomes fullscreen. Technically, this matters only for transparent windows, so, probably not a big deal. And the rest of functionality can be implemented using EWMH, I believe.

I just don't see the big reason to do it right now, as I am not sure of how much Polybar suits xmonad in general and if there is any need for it. However, as mentioned, `ixwindow` is not tied up to polybar one bit, but still, I am not sure of how much public needs this. 

Feel free to implement it yourself and open corresponding PR :)
