### ISSUE TITLE
.hpp error

### ISSUE THREAD

**Issue by blockhead100** [andreykaere/ixwindow#2]
![image](https://user-images.githubusercontent.com/55167737/202359396-e8e532d1-812f-403c-b864-889155de8b71.png)
![image](https://user-images.githubusercontent.com/55167737/202359721-bb0cbe98-a1d7-449d-a4b1-8390138676a1.png)

**Comment by blockhead100** [comment]
i cant believe i did not think of that,
thanks

**Comment by blockhead100** [comment]
I am very new to poly bar and this hole rise thing so sorry for being kind of a dummy.

**Comment by andreykaere** [comment]
You said it was working, what did you do after that to get this error? (I just need kind of steps to reproduce issue)

**Comment by m-debnath** [comment]
I'm getting the same File name too long error after installing libopencv-dev.

@blockhead100 Could you please elaborate how did you resolved this?

I'm on Ubuntu 22.04.

![image](https://user-images.githubusercontent.com/11466723/202866518-cfecb42b-a7ad-4507-94c7-dc4b29b140b4.png)

**Comment by andreykaere** [comment]
I was able to reproduce it on my machine, thank you @m-debnath for pointing it out. Probably some version related issue here. I am gonna investigate tomorrow and will get back to you as soon as I will figure it out.

**Comment by m-debnath** [comment]
Thank you @andreykaere! In the meantime I've created a simple script, which outputs just the icon for the running application. I am using this together with xwindow module. Works well for my need. =)

https://gist.github.com/m-debnath/8b557ff95bb460af3818ece4379878e5

![image](https://user-images.githubusercontent.com/11466723/202903944-824ae41e-cda9-4403-9582-7f31eb0972b4.png)

**Comment by andreykaere** [comment]
Looks nice too! However, it's quite difficult from what this project gives you, basically you're getting a real icon and not an emoji. I use Brave, Alacritty, Telegram very often and I really like to see a good icon and not some emoji replacement. So maybe you can give it a try yourself. And moreover, you don't have to specify icons yourself 99% of the time. But if your script suits you better, so be it :)

**Comment by blockhead100** [comment]
Wow thank so much for finding the fix sorry for not getting back.

**Comment by andreykaere** [comment]
My pleasure! Feel free to reopen issue if problem is not resolved for you or open new issue if you have any other question or problem, will do my best to help you:)

**Comment by blockhead100** [comment]
New error yay 
![image](https://user-images.githubusercontent.com/55167737/202935480-b3fd7ad7-c95e-4fd8-870b-aceb584c392b.jpeg)

Reproduce steps:
I'm running pop_os. 
I installed the package. 
Then I inputed my ixwindow dir. 
![image](https://user-images.githubusercontent.com/55167737/202935876-b604c7c2-3efb-4ebf-8d34-60d5cab481f5.jpeg)
Then I launched poly bar and got the error above.

**Comment by blockhead100** [comment]
I can not reopen lol
sorry

**Comment by andreykaere** [comment]
Are you sure you have bash installed?

**Comment by blockhead100** [comment]
yep bash is installed, I think your script needs to be run as root whtch I dont know how to do with `exec = `

**Comment by andreykaere** [comment]
Of course you don't need to run it as a root. Okay, first of all, can you run it from the command line? Like just `./ixwindow`. Second, show me the output of `ls -l ixwindow` (file, not directory)

**Comment by andreykaere** [comment]
I am glad it worked out for you! I hope you got it working without sudo. If you got it working using sudo, then I advise you to find a way without using sudo.
