### ISSUE TITLE
Initial icon position does not take take the value of "gap_per_desk" into account

### ISSUE THREAD

**Issue by kontroll** [andreykaere/ixwindow#4]
I'm running a multi monitor setup, and i3-wm. When I start polybar (with the ixwindow module configured properly) the icon does not appear in the proper position. It does use the `x` variable value, however, leading me to suspect that the issue is that the current number of workspaces (on a given monitor?) is not checked.

When I change window focus, the icon updates as intended.

When I switch monitors, that's when the position updates to reflect the number of workspaces + the x offset. It's not a huge issue, but all the same... :)

**Comment by andreykaere** [comment]
Hi! Thank you for this issue! Since I don't have a multi monitor setup, I can't really test things. So I am gonna try to fix it and ask you if it works. Is that okay with you?

**Comment by kontroll** [comment]
Sure thing.
